### ISSUE TITLE
Cannot find Xlib

### ISSUE THREAD

**Issue by XeroShi** [CTurt/3DSController#52]
So attempting to run it on my Mac it keeps on giving me this.
Traceback (most recent call last):
  File "/Users/(MacName)/3DSController.py", line 6, in <module>
    import Xlib, Xlib.display, Xlib.XK
ModuleNotFoundError: No module named 'Xlib'
What does this mean?

**Comment by ghost** [comment]
Use in a Terminal:

`pip install Xlib`

Or:

`easy_install Xlib`

**Comment by BertBR** [comment]
I got this error after install Xlib via pip then run 3DSController.py

Running via Termux!

$ ./3DSController.py
Traceback (most recent call last):
  File "./3DSController.py", line 163, in <module>
    disp = Xlib.display.Display()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/Xlib/protocol/display.py", line 85, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/Xlib/support/unix_connect.py", line 61, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
